name: security
description: "A new Flutter project."
resolution: workspace
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  google_fonts: ^8.0.1
  core:
    path: ../../packages/core
  ui:
    path: ../../packages/ui
  rxdart: ^0.28.0
  short_navigation: ^2.5.3
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  flutter_svg: ^2.2.3
  shimmer: ^3.0.0
  flutter_dotenv: ^6.0.0
  pdf: ^3.11.3
  intl: ^0.20.2
  path_provider: ^2.1.5
  open_file: ^3.5.11  
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  package_rename: ^1.10.1
  awesome_flutter_extensions: ^2.0.1
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

package_rename_config:
  android:
    app_name: "Resipal - Security"
    package_name: "app.resipal.security"
  ios:
    app_name: "Resipal - Security"
    bundle_name: "Resipal - Security"
    package_name: "app.resipal.security"