name: resipal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  bloc: ^9.2.0
  change_app_package_name: ^1.5.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  get_it: ^9.2.0
  google_fonts: ^7.0.2
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  logger: ^2.6.2
  package_info_plus: ^9.0.0
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  short_navigation: ^2.5.3
  supabase_flutter: ^2.12.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_native_splash:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#ffffff"
  #background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png/jpg file and should be sized for 4x pixel density.
  image: assets/resipal_logo.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
  # see the Android 12 section below.
  #branding: assets/dart.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png

  # From Android 12 onwards, the splash screen is handled differently than in previous versions.
  # Please visit https://developer.android.com/guide/topics/ui/splash-screen
  # Following are specific parameters for Android 12+.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # If we not properly follow Android guideline. Specfically we need to put our logo inside
    # 160 * 160 diameter circle.     #
    image: assets/logo/tmdb_android_12_logo.png

    # Splash screen background color.
    color: "#ffffff"

    # We can disable splash logic generation for any platform by specifying platform name with true/false
    # for enablement and disablement
    # platform.
  web:
    false
    #android: true
    #ios: true

  # For more configuration kindly check https://pub.dev/packages/flutter_native_splash
